= Hodnocen칤
:note-caption: :information_source:

== Polo쬶y hodnocen칤

Hodnocen칤 p콏edm캩tu se skl치d치 z 캜치st칤 uveden칳ch v n치sleduj칤c칤 tabulce.
Druh칳 sloupe캜ek obsahuje maxim치ln칤 po캜et bod콢, kter칠 mohou studenti z칤skat.
T콏et칤 sloupe캜ek ur캜uje minim치ln칤 po캜et bod콢 nutn칳 k 칰sp캩코n칠mu z칤sk치n칤 z치po캜tu a zn치mky.

[options="autowidth,header"]
|===
| Polo쬶a                                  | Max. po캜. bod콢 | Min. po캜. bod콢
| xref:tasks#[칔lohy] (10)                  | 50             | 25
| xref:semestralka#[Semestr치ln칤 pr치ce] (1) | 50             | 25
| Body za aktivitu                         | 5              | 0
| *Celkem*                                 | 105            | 50
|===

NOTE: V치코 aktu치ln칤 po캜et bod콢 najdete v aplikaci https://grades.fit.cvut.cz/courses/NI-PYT/my-classification[Klasifikace].


== Z치chrann치 칰loha

V p콏칤pad캩, 쬰 m치 student za 칰lohy z hodin (칰koly) na konci semestru alespo켿 15 bod콢,
ale m칠n캩 ne 25, m콢쬰 vypracovat bonusovou 칰lohu dle zad치n칤,
na kter칠m se s vyu캜uj칤c칤mi explicitn캩 dohodne.
Za tuto 칰lohu m콢쬰 dostat a 5 bod콢.
Pokud z칤sk치 alespo켿 2,5, bude mu povoleno z칤skat z치po캜et
(i kdyby celkem na 25 bod콢 z 칰kol콢 nedos치hl; podm칤nka na 25 bod콢 za semestr치lku z콢st치v치 platn치).
V takov칠 p콏칤pad캩 budou body za bonusovou 칰lohu p콏i캜teny k bod콢m z 칰loh,
ale pouze do maxim치ln칤 v칳코e 25.

.P콏칤klad 1
Anna z칤sk치 z 칰loh na konci semestru pouze 22 bod콢,
proto쬰 m캩la moc starost칤 s p콏edm캩tem MI-MPI a nest칤hala 칰lohy v캜as vypracov치vat.
Za norm치ln칤ch okolnost칤 tedy nem치 n치rok na z치po캜et.
Na코t캩st칤 existuje z치chrann치 칰loha.
Tu Anna vypracuje na 5 bod콢.
22 + 5 je 27, tak쬰 celkem kon캜칤 semestr s 25 body (body za z치chranou 칰lohu jsou p콏i캜teny do maxim치ln칤 v칳코e 25).
M콢쬰 odevzdat semestr치lku a kdy dostane aspo켿 25 bod콢, m치 z치po캜et a adekv치tn칤 zn치mku.

.P콏칤klad 2
Robert z칤sk치 z 칰loh na konci semestru jen 18 bod콢.
Z치chrannou 칰lohu vypracuje na 3 body.
Celkem m치 tedy 21 bod콢, co by na z치po캜et nesta캜ilo,
ale proto쬰 vypracoval z치chrannou 칰lohu alespo켿 na 2,5 bodu,
m콢쬰 takt칠 odevzdat semestr치lku a pokud z n칤 bude m칤t alespo켿 25, dostat zn치mku.
Pokud ale nem치 n캩jak칠 body za aktivitu, tak fakticky pot콏ebuje ze semestr치lky alespo켿 29,
jinak by toti dostal F.

.P콏칤klad 3
Pep칤캜ek m치 na konci semestru z 칰loh jen 12 bod콢.
Pep칤캜ek m치 bohu쬰l sm콢lu a z치po캜et nedostane.
Semestr치lku v코ak m콢쬰 vypracovat pro radost.


== Celkov칠 hodnocen칤

[options="autowidth,header"]
|====
| Zn치mka | Bodov칠 rozmez칤 | Slovn칤 hodnocen칤
| **A**  | 90 a v칤ce      | v칳born캩
| **B**  | 80-89          | velmi dob콏e
| **C**  | 70-79          | dob콏e
| **D**  | 60-69          | uspokojiv캩
| **E**  | 50-59          | dostate캜n캩
| **F**  | m칠n캩 ne 50    | nedostate캜n캩
|====

Hodnocen칤 se 콏칤d칤 https://www.cvut.cz/vnitrni-predpisy#szr[游닀 Studijn칤m a zku코ebn칤m 콏치dem 캛VUT], kter칳 najdete na str치nce s https://www.cvut.cz/vnitrni-predpisy[vnit콏n칤mi p콏edpisy 캛VUT].
