= 칔lohy (nejen na doma)
:toc:
:warning-caption: :warning:


Sou캜치st칤 hodnocen칤 jsou p콏edev코칤m 칰lohy.
Uv칤t치me, pokud je budete 콏e코it na cvi캜en칤ch, po skon캜en칤 v칳kladu.
R치di v치m porad칤me osobn캩.
Co nestihnete na cvi캜en칤ch, dod캩l치te doma.
R치di v치m porad칤me i v GitHub issue.

Hotov칠 칰lohy odevzd치te jako gitov칳 repozit치콏 na https://github.com[GitHubu],
p콏칤padn캩 fakultn칤m https://gitlab.fit.cvut.cz[GitLabu].
V obou p콏칤padech n치m nezapome켿te
https://help.github.com/articles/inviting-collaborators-to-a-personal-repository/[d치t p콏칤stup].

Vzhledem k tomu, 쬰 v코ichni m치te stejn칠 zad치n칤, doporu캜ujeme pou쮂셦 priv치tn칤
repozit치콏. Sv콢j k칩d m콢쬰te zve콏ejnit pod n캩jakou open-source licenc칤 po na코em
zkontrolov치n칤 v코ech navazuj칤c칤ch 칰loh.

Odkaz na (nov칳) repozit치콏 n치m po코lete e-mailem.
Pro odevzd치n칤 v repozit치콏i v쬯y nastav칤te nov칳 tag, dle zad치n칤 칰lohy.

Term칤n odevzd치n칤 칰lohy je zpravidla pond캩l칤 (v캜etn캩) 12 dn칤 po cvi캜en칤,
na kter칠m byl 칰kol zad치n.
U n캩kter칳ch 칰loh se term칤n m콢쬰 li코it,
je u nich symbol 游꺖 (term칤n prodlou쬰n), nebo 游 (term칤n zkr치cen).

== 칔loha filabel (CLI): 22.10.2018 游꺖

Va코칤m 칰kolem za 5 bod콢 je vytvo콏it command line aplikaci pracuj칤c칤 s GitHub API,
pomoc칤 knihoven http://docs.python-requests.org[requests] a
http://click.pocoo.org[click].

Aplikace slou쮂 ke 코t칤tkov치n칤 (labelov치n칤) Pull Request콢 (PR) na GitHub podle
soubor콢, kter칠 se m캩n칤. P콏칤klad: Kdy va코e aplikace zjist칤, 쬰 PR m캩n칤 soubor
`templates/cool.html`, nastav칤 코t칤tek `templates`. Kdy zjist칤, 쬰 m캩n칤 soubor
`README.rst`, nastav칤 코t칤tek `docs` apod.

Zad치n칤 a testy::
  https://github.com/cvut/filabel/tree/basic[github.com/cvut/filabel @basic]

== 칔loha filabel (webov치 aplikace): 22.10.2018

Va코칤m 칰kolem za 5 bod콢 je p콏idat do apliakce *filabel* webov칳 server,
kter칳 bude reagovat na ud치losti na GitHubu automaticky.
Pou쬴jete webov칳 framework http://flask.pocoo.org/[Flask].

Zad치n칤 a testy::
  https://github.com/cvut/filabel/tree/web[github.com/cvut/filabel @web]
