= 칔lohy (nejen na doma)
:toc:
:warning-caption: :warning:


Sou캜치st칤 hodnocen칤 jsou p콏edev코칤m 칰lohy.
Uv칤t치me, pokud je budete 콏e코it na cvi캜en칤ch, po skon캜en칤 v칳kladu.
R치di v치m porad칤me osobn캩.
Co nestihnete na cvi캜en칤ch, dod캩l치te doma.
R치di v치m porad칤me i v GitHub issue.

Hotov칠 칰lohy odevzd치te jako gitov칳 repozit치콏 na https://github.com[GitHubu],
p콏칤padn캩 fakultn칤m https://gitlab.fit.cvut.cz[GitLabu].
V obou p콏칤padech n치m nezapome켿te
https://help.github.com/articles/inviting-collaborators-to-a-personal-repository/[d치t p콏칤stup].
Na GitHubu jsme jako https://github.com/hroncok[hroncok] a https://github.com/MarekSuchanek[MarekSuchanek].
Na GitLabu jako hroncmir a suchama4.

Vzhledem k tomu, 쬰 v코ichni m치te stejn칠 zad치n칤, doporu캜ujeme pou쮂셦 priv치tn칤
repozit치콏. Sv콢j k칩d m콢쬰te zve콏ejnit pod n캩jakou open-source licenc칤 po na코em
zkontrolov치n칤 v코ech navazuj칤c칤ch 칰loh.

Odkaz na (nov칳) repozit치콏 n치m po코lete e-mailem.
Pro odevzd치n칤 v repozit치콏i v쬯y nastav칤te nov칳 tag, dle zad치n칤 칰lohy.

Term칤n odevzd치n칤 칰lohy je zpravidla pond캩l칤 (v캜etn캩) 12 dn칤 po cvi캜en칤,
na kter칠m byl 칰kol zad치n.
U n캩kter칳ch 칰loh se term칤n m콢쬰 li코it,
je u nich symbol 游꺖 (term칤n prodlou쬰n), nebo 游 (term칤n zkr치cen).

== 칔loha filabel (CLI): 22.10.2018 游꺖

Va코칤m 칰kolem za 5 bod콢 je vytvo콏it command line aplikaci pracuj칤c칤 s GitHub API,
pomoc칤 knihoven http://docs.python-requests.org[requests] a
http://click.pocoo.org[click].

Aplikace slou쮂 ke 코t칤tkov치n칤 (labelov치n칤) Pull Request콢 (PR) na GitHub podle
soubor콢, kter칠 se m캩n칤. P콏칤klad: Kdy va코e aplikace zjist칤, 쬰 PR m캩n칤 soubor
`templates/cool.html`, nastav칤 코t칤tek `templates`. Kdy zjist칤, 쬰 m캩n칤 soubor
`README.rst`, nastav칤 코t칤tek `docs` apod.

Zad치n칤 a testy::
  https://github.com/cvut/filabel/tree/basic[github.com/cvut/filabel @basic]

== 칔loha filabel (webov치 aplikace): 22.10.2018

Va코칤m 칰kolem za 5 bod콢 je p콏idat do aplikace *filabel* webov칳 server,
kter칳 bude reagovat na ud치losti na GitHubu automaticky.
Pou쬴jete webov칳 framework http://flask.pocoo.org/[Flask].

Zad치n칤 a testy::
  https://github.com/cvut/filabel/tree/web[github.com/cvut/filabel @web]

== 칔loha Pandas: 29.10.2018

Va코im 칰kolem za 5 bod콢 je analyzovat v칳sledky **Python Developers Survey**,
odpov캩d캩t na ot치zky a vy콏e코it 칰koly ve frameworku Pandas.

Zad치n칤::
  xref:_tasks/pandas#[칔loha Pandas]

== 칔loha filabel (bal칤캜ek): 5.11.2018

Va코칤m 칰kolem za 5 bod콢 je ud캩lat z va코eho dosavadn칤ho projektu *filabel*
bal칤캜ek instalovateln칳 p콏es pip a nahr치t jej na testovac칤 PyPI.

Zad치n칤 a testy::
  https://github.com/cvut/filabel/tree/modular[github.com/cvut/filabel @modular]
  
== 칔loha beeclust (numpy): 12.11.2018

Va코칤m 칰kolem za 5 bod콢 je implementovat dle zad치n칤 simulaci shlukovac칤ho algoritmu
http://heikohamann.de/pub/schmickl_beeclust_2011.pdf[BeeClust] pomoc칤 knihovny 
http://www.numpy.org[numpy].

Zad치n칤 a testy::
  https://github.com/cvut/beeclust/tree/basic[github.com/cvut/beeclust @basic]

== 칔loha filabel (testov치n칤): 19.11.2018

Va코칤m 칰kolem za 5 bod콢 je napsat k va코emu dosavadn칤mu projektu *filabel* testy 
s pou쬴t칤m https://docs.pytest.org/en/latest/[pytest] (a p콏칤padn캩 dal코칤ch knihoven), 
umo쬹it spou코t캩n칤 test콢 pomoc칤 `setup.py` a spou코t캩t testy tak칠 na 
https://travis-ci.org[Travis CI].

Zad치n칤::
  https://github.com/cvut/filabel/tree/tests[github.com/cvut/filabel @tests]
  
== 칔loha beeclust (zrychlen칤): 26.11.2018

Va코칤m 칰kolem za 5 bod콢 je zrychlit implementaci simulace shlukovac칤ho algoritmu
http://heikohamann.de/pub/schmickl_beeclust_2011.pdf[BeeClust] s vyu쬴t칤m 
https://cython.readthedocs.io/[Cythonu] tak, aby dok치zala 
v rozumn칠m 캜ase (viz zad치n칤) pracovat s v캩t코칤mi mapami.

Zad치n칤 a testy::
  https://github.com/cvut/beeclust/tree/speedup[github.com/cvut/beeclust @speedup]

== 칔loha filabel (testov치n칤): 3.12.2018

Va코칤m 칰kolem za 5 bod콢 je napsat k va코emu dosavadn칤mu projektu *filabel* dokumentaci 
pomoc칤 http://www.sphinx-doc.org[Sphinx], kter치 bude popisovat, jak s aplikac칤 pracovat i
jak funguje uvnit콏, a to v캜etn캩 doctest콢, kter칠 pob캩쮂 tak칠 na https://travis-ci.org[Travis CI]
spole캜n캩 s testy z minul칠ho 칰kolu.

Zad치n칤::
  https://github.com/cvut/filabel/tree/tests[github.com/cvut/filabel @docs]
